# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: sourceBranch
  type: string
  default: $(Build.SourceBranch)
- name: environment
  type: string
  default: 'dev'
  values:
    - 'dev'
    - 'test'

trigger:
 branches:
  include:
  - dev-1
  - test-1

pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: map_branch_with_env
  jobs:
  - job: map_branch_with_env
    steps:
    - checkout: none
    - script: |
         echo "Build.SourceBranch: $(Build.SourceBranch)"
         echo "Build.Reason: $(Build.Reason)"
         if [ "$(Build.Reason)" == "Manual" ]; then
          echo "##vso[task.setvariable variable=environment;isOutput=true]${{ parameters.environment }}"
          echo '$(environment)'
         else
          branch=$(echo $(Build.SourceBranch) | sed 's|refs/heads/||')
          if [[ $branch == 'dev-1' ]]; then
            echo "##vso[task.setvariable variable=environment;isOutput=true]dev"
          elif [[ $branch == 'test-1' ]]; then
            echo "##vso[task.setvariable variable=environment;isOutput=true]test"
          fi
         fi
         echo "setenv.environment: $(environment)"
      name: setenv

- stage: deploy_dev
  displayName: deploy_dev
  condition: eq(dependencies.map_branch_with_env.outputs['setenv.environment'], 'dev')
  jobs:
    - job: deploy_dev
      steps:
      - script: |
          echo "$(dependencies.map_branch_with_env.outputs['setenv.environment'])"

- stage: deploy_test
  displayName: deploy_test
  condition: eq(dependencies.map_branch_with_env.outputs['setenv.environment'], 'dev')
  jobs:
    - job: deploy_test
      steps:
      
      - script: |
          echo "$(dependencies.map_branch_with_env.outputs['setenv.environment'])"
      
      

