# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - test

trigger:
 branches:
  include:
  - dev-1
  - test-1

pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: map_branch_with_env
  jobs:
  - job: map_branch_with_env
    steps:
    - checkout: none
    - script: |
         branch=$(echo $(Build.SourceBranch) | sed 's|refs/heads/||')
         if [[ $branch == 'dev-1' ]]; then
          echo "##vso[task.setvariable variable=environment]dev"
         elif [[ $branch == 'test-1' ]]; then
          echo "##vso[task.setvariable variable=environment]test"
         fi

- stage: deploy_dev
  displayName: deploy_dev
  condition: eq('${{ parameters.environment }}', 'dev')
  jobs:
    - job: deploy_dev
      steps:
      - script: |
          echo "deploy to dev env"
          echo $(environment)

- stage: deploy_test
  displayName: deploy_test
  condition: eq('${{ parameters.environment }}', 'test')
  jobs:
    - job: deploy_test
      steps:
      - script: |
          echo "deploy to test env"
          echo $(environment)
      
      

