# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: environment
  type: string
  default: 'dev'
  values:
    - 'dev'
    - 'test'

- name: sourceBranch
  type: string
  default: $(Build.SourceBranch)

trigger:
 branches:
  include:
  - dev-1
  - test-1

pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: map_env_with_branch
  displayName: map_env_with_branch
  jobs:
    - job: map_env_with_branch
      steps:
        # - script: |
        #    if [ "$(Build.Reason)" == "Manual" ]; then
        #      echo "##vso[task.setvariable variable=environment;isOutput=true]$(parameters.environment)"
        #    else
        #      branch=$(echo $(Build.SourceBranch) | sed 's|refs/heads/||')
        #      if [[ $branch == 'dev-3.2' ]]; then
        #        echo "##vso[task.setvariable variable=environment;isOutput=true]dev"
        #      elif [[ $branch == 'dev-3.0-dev' ]]; then
        #        echo "##vso[task.setvariable variable=environment;isOutput=true]qas"
        #      elif [[ $branch == 'master-3.0' ]]; then
        #        echo "##vso[task.setvariable variable=environment;isOutput=true]prod"
        #      fi
        #    fi
      - script: |
          if [ "$(Build.Reason)" == "Manual" ]; then
            echo "##vso[task.setvariable variable=environment;isOutput=true]$(parameters.environment)"
          else
            branch=$(echo $(Build.SourceBranch) | sed 's|refs/heads/||')
            if [[ $branch == 'dev-1' ]]; then
              echo "##vso[task.setvariable variable=environment;isOutput=true]dev"
            elif [[ $branch == 'test-1' ]]; then  
              echo "##vso[task.setvariable variable=environment;isOutput=true]test"
            fi
          fi
          name: map_env_with_branch

- stage: deploy_dev
  dependsOn: map_env_with_branch
  displayName: deploy_dev
  variables:
    deploy_env: $[stageDependencies.map_env_with_branch.map_env_with_branch.outputs['map_env_with_branch.environment']]
  condition: eq('$(deploy_env)', 'dev')
  jobs:
    - job: deploy_dev
      steps:
      
      - script: |
          echo "deploy to $(deploy_env) env"

- stage: deploy_test
  dependsOn: map_env_with_branch
  displayName: deploy_test
  variables:
    deploy_env: $[stageDependencies.map_env_with_branch.map_env_with_branch.outputs['map_env_with_branch.environment']] 
  condition: eq('$(deploy_env)', 'test')
  jobs:
    - job: deploy_test
      steps:     
      - script: |
          echo "deploy to $(deploy_env) env"
      
      

