parameters:
- name: environment
  type: string
  default: 'dev'
  values:
    - 'dev'
    - 'qas'
    - 'prod'
  
- name: condition
  type: string
  default: 'succeeded()'

stages:
- stage: Build
  condition: always()
  dependsOn: map_env_with_branch
  displayName: 'Install NodeJS and Build'

  jobs:
  - job: Build
    displayName: 'Install nodejs and Build'
    steps:
    - task: NodeTool@0
      displayName: 'Use Node.js tool'
      inputs:
        versionSpec: '20.14.x'
    
    - script: |
        npm install -g yarn
      condition: eq('${{ parameters.environment }}', 'dev')
      displayName: 'Build dev'

    - script: |
        npm cache clean -f
      condition: eq('${{ parameters.environment }}', 'qas')
      displayName: 'Build qas'
      
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/dist'
        artifact: 'blueprint'
        publishLocation: 'pipeline'


       



