parameters:
- name: environment
  type: string
  default: 'dev'
  values:
    - 'dev'
    - 'qas'
    - 'prod'
  
- name: condition
  type: string
  default: 'succeeded()'

stages:
- stage: Build
  condition: always()
  displayName: 'Install NodeJS and Build'

  jobs:
  - job: Build
    displayName: 'Install nodejs and Build'
    steps:
    - task: NodeTool@0
      displayName: 'Use Node.js tool'
      inputs:
        versionSpec: '20.14.x'
    
    - script: |
        npm install -g yarn
        yarn cache clean
        yarn install --frozen-lockfile
        yarn build:dev adm
      condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/dev-3.2'), eq('${{ parameters.environment }}', 'dev'))
      displayName: 'Build dev'

    - script: |
        npm cache clean -f
        npm ci
        npm --version
        npm run build-all-qa
      condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/dev-3.0-dev'), eq('${{ parameters.environment }}', 'qas'))
      displayName: 'Build qas'
      
    - script: |
        npm ci
        npm --version
        npm run build-all-prod
      condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/main-3.0'), eq('${{ parameters.environment }}', 'prod')) 
      displayName: 'Build prod'
      
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/dist'
        artifact: 'blueprint'
        publishLocation: 'pipeline'


       



